# Generated by Django 5.1.3 on 2024-12-16 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='kolej',
        ),
    ]
