# Generated by Django 5.1.3 on 2024-12-16 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0003_mentor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='description',
            new_name='mentorName',
        ),
    ]
